[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Asset URLs will be set in Netlify environment variables
# These are just examples and will be overridden by the Netlify UI settings

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
